//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/17/2017 06:02:20
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Contoso.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Welcome to Contoso!"
        /// </summary>
        public static string ApplicationDescription
        {
            get
            {
                return resourceLoader.GetString("ApplicationDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Contoso"
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return resourceLoader.GetString("ApplicationName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "adenwala@outlook.com"
        /// </summary>
        public static string ApplicationSupportEmailAddress
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportEmailAddress");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "@madenwal"
        /// </summary>
        public static string ApplicationSupportTwitterUsername
        {
            get
            {
                return resourceLoader.GetString("ApplicationSupportTwitterUsername");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Theme will be applied the next time you launch the application."
        /// </summary>
        public static string ApplicationThemeStatus
        {
            get
            {
                return resourceLoader.GetString("ApplicationThemeStatus");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "LeftToRight"
        /// </summary>
        public static string ResourceFlowDirection
        {
            get
            {
                return resourceLoader.GetString("ResourceFlowDirection");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "en-US"
        /// </summary>
        public static string ResourceLanguage
        {
            get
            {
                return resourceLoader.GetString("ResourceLanguage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string TextAbout
        {
            get
            {
                return resourceLoader.GetString("TextAbout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Allow"
        /// </summary>
        public static string TextAllow
        {
            get
            {
                return resourceLoader.GetString("TextAllow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Details"
        /// </summary>
        public static string TextDetails
        {
            get
            {
                return resourceLoader.GetString("TextDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Downloading..."
        /// </summary>
        public static string TextDownloading
        {
            get
            {
                return resourceLoader.GetString("TextDownloading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Home"
        /// </summary>
        public static string TextHome
        {
            get
            {
                return resourceLoader.GetString("TextHome");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin to Start"
        /// </summary>
        public static string TextPinToStart
        {
            get
            {
                return resourceLoader.GetString("TextPinToStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please wait..."
        /// </summary>
        public static string TextPleaseWait
        {
            get
            {
                return resourceLoader.GetString("TextPleaseWait");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Privacy Statement"
        /// </summary>
        public static string TextPrivacyStatement
        {
            get
            {
                return resourceLoader.GetString("TextPrivacyStatement");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Anonymous usage data may be collected to improve the application.  Outside of that, this app does not collection any information about you nor transmit any information except that which you would normally expect in any web request (such as IP address). If you choose to enable location services, then you last known location is stored in the app anonymously so that the app loads quicker the next time it is launched."
        /// </summary>
        public static string TextPrivacyStatementDescription
        {
            get
            {
                return resourceLoader.GetString("TextPrivacyStatementDescription");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Rate Application"
        /// </summary>
        public static string TextRateApp
        {
            get
            {
                return resourceLoader.GetString("TextRateApp");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Refresh"
        /// </summary>
        public static string TextRefresh
        {
            get
            {
                return resourceLoader.GetString("TextRefresh");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string TextSettings
        {
            get
            {
                return resourceLoader.GetString("TextSettings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Share"
        /// </summary>
        public static string TextShare
        {
            get
            {
                return resourceLoader.GetString("TextShare");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sort"
        /// </summary>
        public static string TextSort
        {
            get
            {
                return resourceLoader.GetString("TextSort");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sorting..."
        /// </summary>
        public static string TextSorting
        {
            get
            {
                return resourceLoader.GetString("TextSorting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Submit"
        /// </summary>
        public static string TextSubmit
        {
            get
            {
                return resourceLoader.GetString("TextSubmit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "General"
        /// </summary>
        public static string TextTitleGeneral
        {
            get
            {
                return resourceLoader.GetString("TextTitleGeneral");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unpin from Start"
        /// </summary>
        public static string TextUnpinFromStart
        {
            get
            {
                return resourceLoader.GetString("TextUnpinFromStart");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string ViewTitleAbout
        {
            get
            {
                return resourceLoader.GetString("ViewTitleAbout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string ViewTitleSettings
        {
            get
            {
                return resourceLoader.GetString("ViewTitleSettings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Welcome!"
        /// </summary>
        public static string ViewTitleWelcome
        {
            get
            {
                return resourceLoader.GetString("ViewTitleWelcome");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Requesting..."
        /// </summary>
        public static string TextRequesting
        {
            get
            {
                return resourceLoader.GetString("TextRequesting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Retrieving more data..."
        /// </summary>
        public static string TextRetrievingMoreData
        {
            get
            {
                return resourceLoader.GetString("TextRetrievingMoreData");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pull to Refresh"
        /// </summary>
        public static string TextPullToRefresh
        {
            get
            {
                return resourceLoader.GetString("TextPullToRefresh");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Release to Refresh"
        /// </summary>
        public static string TextReleaseToRefresh
        {
            get
            {
                return resourceLoader.GetString("TextReleaseToRefresh");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Loading..."
        /// </summary>
        public static string TextLoading
        {
            get
            {
                return resourceLoader.GetString("TextLoading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "N/A"
        /// </summary>
        public static string TextNotApplicable
        {
            get
            {
                return resourceLoader.GetString("TextNotApplicable");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Privacy Policy"
        /// </summary>
        public static string ViewTitlePrivacyPolicy
        {
            get
            {
                return resourceLoader.GetString("ViewTitlePrivacyPolicy");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Terms of Service"
        /// </summary>
        public static string ViewTitleTermsOfService
        {
            get
            {
                return resourceLoader.GetString("ViewTitleTermsOfService");
            }
        }
    }
}
