//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/17/2017 06:17:22
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace AppFramework.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Account
    {
        
        private static ResourceLoader resourceLoader;
        
        static Account()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Account).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Account");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Account");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Authenticating..."
        /// </summary>
        public static string TextAuthenticating
        {
            get
            {
                return resourceLoader.GetString("TextAuthenticating");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "N/A"
        /// </summary>
        public static string TextNotApplicable
        {
            get
            {
                return resourceLoader.GetString("TextNotApplicable");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Signing out..."
        /// </summary>
        public static string TextSigningOut
        {
            get
            {
                return resourceLoader.GetString("TextSigningOut");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign out"
        /// </summary>
        public static string TextSignout
        {
            get
            {
                return resourceLoader.GetString("TextSignout");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Are you sure you want to sign out?"
        /// </summary>
        public static string TextSignoutConfirmation
        {
            get
            {
                return resourceLoader.GetString("TextSignoutConfirmation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unauthorized user..."
        /// </summary>
        public static string TextUnauthorizedUser
        {
            get
            {
                return resourceLoader.GetString("TextUnauthorizedUser");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sign-In / Sign-Up with an account that you can associate with {0}."
        /// </summary>
        public static string TextWebAccountManagerSignUpDescription
        {
            get
            {
                return resourceLoader.GetString("TextWebAccountManagerSignUpDescription");
            }
        }
    }
}
