//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Core.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Core.Strings.Account", typeof(Account).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btnRegister_Content {
            get {
                return ResourceManager.GetString("btnRegister.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string btnSignin_Content {
            get {
                return ResourceManager.GetString("btnSignin.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string btnSignout_Content {
            get {
                return ResourceManager.GetString("btnSignout.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string lnkForgotPassword_Content {
            get {
                return ResourceManager.GetString("lnkForgotPassword.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Contoso! Register for an account to enjoy all the service offerings we provide..
        /// </summary>
        public static string tbWelcomeDescription_Text {
            get {
                return ResourceManager.GetString("tbWelcomeDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string TextAuthenticating {
            get {
                return ResourceManager.GetString("TextAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. Try again later..
        /// </summary>
        public static string TextAuthenticationFailed {
            get {
                return ResourceManager.GetString("TextAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account....
        /// </summary>
        public static string TextCreatingAccount {
            get {
                return ResourceManager.GetString("TextCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username was not found!.
        /// </summary>
        public static string TextUsernameNotFound {
            get {
                return ResourceManager.GetString("TextUsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating username....
        /// </summary>
        public static string TextValidatingUsername {
            get {
                return ResourceManager.GetString("TextValidatingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to use your {0} profile to register an account. Please try again later..
        /// </summary>
        public static string TextWebAccountManagerRegisterAccountFailure {
            get {
                return ResourceManager.GetString("TextWebAccountManagerRegisterAccountFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving your {0} profile....
        /// </summary>
        public static string TextWebAccountManagerRetrievingProfile {
            get {
                return ResourceManager.GetString("TextWebAccountManagerRetrievingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string TextWelcomeAuthenticated {
            get {
                return ResourceManager.GetString("TextWelcomeAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string TextWelcomeUnauthenticated {
            get {
                return ResourceManager.GetString("TextWelcomeUnauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1:.
        /// </summary>
        public static string txtAddress1_Header {
            get {
                return ResourceManager.GetString("txtAddress1.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2:.
        /// </summary>
        public static string txtAddress2_Header {
            get {
                return ResourceManager.GetString("txtAddress2.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string txtCity_Header {
            get {
                return ResourceManager.GetString("txtCity.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string txtFirstName_Header {
            get {
                return ResourceManager.GetString("txtFirstName.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string txtLastName_Header {
            get {
                return ResourceManager.GetString("txtLastName.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string txtPassword_Header {
            get {
                return ResourceManager.GetString("txtPassword.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string txtPassword2_Header {
            get {
                return ResourceManager.GetString("txtPassword2.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code:.
        /// </summary>
        public static string txtPostalCode_Header {
            get {
                return ResourceManager.GetString("txtPostalCode.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string txtState_Header {
            get {
                return ResourceManager.GetString("txtState.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string txtUsername_Header {
            get {
                return ResourceManager.GetString("txtUsername.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ViewTitleForgotPassword {
            get {
                return ResourceManager.GetString("ViewTitleForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string ViewTitleSignIn {
            get {
                return ResourceManager.GetString("ViewTitleSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string ViewTitleSignUp {
            get {
                return ResourceManager.GetString("ViewTitleSignUp", resourceCulture);
            }
        }
    }
}
