//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Core.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Core.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string abtnAdd_Label {
            get {
                return ResourceManager.GetString("abtnAdd.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string abtnGoBack_Label {
            get {
                return ResourceManager.GetString("abtnGoBack.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        public static string abtnGoForward_Label {
            get {
                return ResourceManager.GetString("abtnGoForward.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string abtnHome_Label {
            get {
                return ResourceManager.GetString("abtnHome.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        public static string abtnOpenNewWindow_Label {
            get {
                return ResourceManager.GetString("abtnOpenNewWindow.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string abtnPin_Label {
            get {
                return ResourceManager.GetString("abtnPin.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string abtnRefresh_Label {
            get {
                return ResourceManager.GetString("abtnRefresh.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string abtnSave_Label {
            get {
                return ResourceManager.GetString("abtnSave.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string abtnSettings_Label {
            get {
                return ResourceManager.GetString("abtnSettings.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string abtnShare_Label {
            get {
                return ResourceManager.GetString("abtnShare.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string abtnSort_Label {
            get {
                return ResourceManager.GetString("abtnSort.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin from start.
        /// </summary>
        public static string abtnUnpin_Label {
            get {
                return ResourceManager.GetString("abtnUnpin.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Contoso!.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adenwala@outlook.com.
        /// </summary>
        public static string ApplicationSupportEmailAddress {
            get {
                return ResourceManager.GetString("ApplicationSupportEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @madenwal.
        /// </summary>
        public static string ApplicationSupportTwitterUsername {
            get {
                return ResourceManager.GetString("ApplicationSupportTwitterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme will be applied the next time you launch the application..
        /// </summary>
        public static string ApplicationThemeStatus {
            get {
                return ResourceManager.GetString("ApplicationThemeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string asbSearch_PlaceholderText {
            get {
                return ResourceManager.GetString("asbSearch.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel_Content {
            get {
                return ResourceManager.GetString("btnCancel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Jumplist.
        /// </summary>
        public static string btnClearJumplist_Content {
            get {
                return ResourceManager.GetString("btnClearJumplist.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string btnManage_Content {
            get {
                return ResourceManager.GetString("btnManage.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string btnRateApp_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("btnRateApp.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string btnRateApp_Content {
            get {
                return ResourceManager.GetString("btnRateApp.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string btnRateApp_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("btnRateApp.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSubmit_Content {
            get {
                return ResourceManager.GetString("btnSubmit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Feedback.
        /// </summary>
        public static string btnSubmitFeedback_Content {
            get {
                return ResourceManager.GetString("btnSubmitFeedback.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string btnTryAgain_Content {
            get {
                return ResourceManager.GetString("btnTryAgain.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable full logging.
        /// </summary>
        public static string chkEnableFullDebugging_Content {
            get {
                return ResourceManager.GetString("chkEnableFullDebugging.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string lnkPrivacyPolicy_Content {
            get {
                return ResourceManager.GetString("lnkPrivacyPolicy.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us an e-mail.
        /// </summary>
        public static string lnkSendSupportEmail_Content {
            get {
                return ResourceManager.GetString("lnkSendSupportEmail.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string lnkTermsOfService_Content {
            get {
                return ResourceManager.GetString("lnkTermsOfService.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string pbtnFeedback_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("pbtnFeedback.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string pbtnFeedback_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("pbtnFeedback.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string pbtnRateApp_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("pbtnRateApp.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string pbtnRateApp_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("pbtnRateApp.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana.
        /// </summary>
        public static string piCortana_Header {
            get {
                return ResourceManager.GetString("piCortana.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string rdoAppThemeDark_Content {
            get {
                return ResourceManager.GetString("rdoAppThemeDark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string rdoAppThemeDefault_Content {
            get {
                return ResourceManager.GetString("rdoAppThemeDefault.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string rdoAppThemeLight_Content {
            get {
                return ResourceManager.GetString("rdoAppThemeLight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string svbHome_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("svbHome.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string svbHome_Content {
            get {
                return ResourceManager.GetString("svbHome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string svbHome_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("svbHome.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string svbSearch_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("svbSearch.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string svbSearch_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("svbSearch.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string svbSettings_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("svbSettings.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string svbSettings_Content {
            get {
                return ResourceManager.GetString("svbSettings.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string svbSettings_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("svbSettings.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string svbSignIn_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("svbSignIn.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string svbSignIn_Content {
            get {
                return ResourceManager.GetString("svbSignIn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string svbSignIn_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("svbSignIn.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string svbSignout_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("svbSignout.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string svbSignout_ToolTipService_ToolTip {
            get {
                return ResourceManager.GetString("svbSignout.ToolTipService.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Diagnostics.
        /// </summary>
        public static string tbAppDiagnostics_Text {
            get {
                return ResourceManager.GetString("tbAppDiagnostics.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string tbAppTheme_Text {
            get {
                return ResourceManager.GetString("tbAppTheme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Tasks.
        /// </summary>
        public static string tbBackgroundTasks_Text {
            get {
                return ResourceManager.GetString("tbBackgroundTasks.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all voice and typed questions for Cortana with &quot;Show me...&quot;.
        /// </summary>
        public static string tbCortanaBody_Text {
            get {
                return ResourceManager.GetString("tbCortanaBody.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me details of Runtime Two
        ///Show me details of Runtime Four
        ///Show me details of Runtime 6
        ///Show me details of Runtime 13.
        /// </summary>
        public static string tbCortanaExamplesBody_Text {
            get {
                return ResourceManager.GetString("tbCortanaExamplesBody.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, you can ask:.
        /// </summary>
        public static string tbCortanaExamplesHeader_Text {
            get {
                return ResourceManager.GetString("tbCortanaExamplesHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for using Cortana.
        /// </summary>
        public static string tbCortanaHeader_Text {
            get {
                return ResourceManager.GetString("tbCortanaHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this enabled, if this app crashes or you send an e-mail to support, full diagnostics information will be available to the development team to diagnose any issues..
        /// </summary>
        public static string tbEnableFullDebuggingDescription_Text {
            get {
                return ResourceManager.GetString("tbEnableFullDebuggingDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string tbManage_Text {
            get {
                return ResourceManager.GetString("tbManage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string tbSignOut_Text {
            get {
                return ResourceManager.GetString("tbSignOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string tbSupport_Text {
            get {
                return ResourceManager.GetString("tbSupport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured..
        /// </summary>
        public static string tbTryAgain_Text {
            get {
                return ResourceManager.GetString("tbTryAgain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string tbVersion_Text {
            get {
                return ResourceManager.GetString("tbVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string TextAllow {
            get {
                return ResourceManager.GetString("TextAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TextDetails {
            get {
                return ResourceManager.GetString("TextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string TextDownloading {
            get {
                return ResourceManager.GetString("TextDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TextHome {
            get {
                return ResourceManager.GetString("TextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string TextNotApplicable {
            get {
                return ResourceManager.GetString("TextNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextOk {
            get {
                return ResourceManager.GetString("TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string TextPinToStart {
            get {
                return ResourceManager.GetString("TextPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string TextPleaseWait {
            get {
                return ResourceManager.GetString("TextPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string TextPrivacyStatement {
            get {
                return ResourceManager.GetString("TextPrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous usage data may be collected to improve the application.  Outside of that, this app does not collection any information about you nor transmit any information except that which you would normally expect in any web request (such as IP address). If you choose to enable location services, then you last known location is stored in the app anonymously so that the app loads quicker the next time it is launched..
        /// </summary>
        public static string TextPrivacyStatementDescription {
            get {
                return ResourceManager.GetString("TextPrivacyStatementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull to Refresh.
        /// </summary>
        public static string TextPullToRefresh {
            get {
                return ResourceManager.GetString("TextPullToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Application.
        /// </summary>
        public static string TextRateApp {
            get {
                return ResourceManager.GetString("TextRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string TextRefresh {
            get {
                return ResourceManager.GetString("TextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to Refresh.
        /// </summary>
        public static string TextReleaseToRefresh {
            get {
                return ResourceManager.GetString("TextReleaseToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting....
        /// </summary>
        public static string TextRequesting {
            get {
                return ResourceManager.GetString("TextRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving more data....
        /// </summary>
        public static string TextRetrievingMoreData {
            get {
                return ResourceManager.GetString("TextRetrievingMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TextSettings {
            get {
                return ResourceManager.GetString("TextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string TextShare {
            get {
                return ResourceManager.GetString("TextShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string TextSort {
            get {
                return ResourceManager.GetString("TextSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting....
        /// </summary>
        public static string TextSorting {
            get {
                return ResourceManager.GetString("TextSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string TextSubmit {
            get {
                return ResourceManager.GetString("TextSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TextTitleGeneral {
            get {
                return ResourceManager.GetString("TextTitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin from Start.
        /// </summary>
        public static string TextUnpinFromStart {
            get {
                return ResourceManager.GetString("TextUnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull to refresh.
        /// </summary>
        public static string txtPullToRefresh_Text {
            get {
                return ResourceManager.GetString("txtPullToRefresh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ViewTitleAbout {
            get {
                return ResourceManager.GetString("ViewTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string ViewTitlePrivacyPolicy {
            get {
                return ResourceManager.GetString("ViewTitlePrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ViewTitleSettings {
            get {
                return ResourceManager.GetString("ViewTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string ViewTitleTermsOfService {
            get {
                return ResourceManager.GetString("ViewTitleTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string ViewTitleWelcome {
            get {
                return ResourceManager.GetString("ViewTitleWelcome", resourceCulture);
            }
        }
    }
}
