//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/17/2017 06:04:49
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Contoso.Core.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Location
    {
        
        private static ResourceLoader resourceLoader;
        
        static Location()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Location).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Location");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Location");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Determining address..."
        /// </summary>
        public static string TextGeocodingAddress
        {
            get
            {
                return resourceLoader.GetString("TextGeocodingAddress");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location access has not been enabled for this app. Use the manage button and ensure this app has been enabled to use location services."
        /// </summary>
        public static string TextLocationServicesDisabledStatus
        {
            get
            {
                return resourceLoader.GetString("TextLocationServicesDisabledStatus");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Location services is turned off or not enabled for this application. Please enable location from your device settings."
        /// </summary>
        public static string TextLocationServicesNotEnabled
        {
            get
            {
                return resourceLoader.GetString("TextLocationServicesNotEnabled");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Finding your location..."
        /// </summary>
        public static string TextDeterminingLocation
        {
            get
            {
                return resourceLoader.GetString("TextDeterminingLocation");
            }
        }
    }
}
